#!/usr/bin/env python
# -*- coding: utf-8 -*- 

RAW_IDEAS=['Mind Map of HackathonProjects.tk google doc: IdeaMap.tk <http://www.mindmeister.com/223188451>',\
'Workflow sharing -- start up idea is to take the workflows of top students and make/sell complete sets of customize materials to help other people adopt the workflows of the super productive people.I think that thats half the battle, getting into the right life-rhythm. I bet for each stereotype of person, you can find some sort of optimize workflowand then you go and get the workflow kit for the type of person you are like are you like riley or (racks brains) my friend jenny or like cj whose system do you use well fine the person you learn like you could even make "learn like riley" or "learn like a thiel fellow" or "learn like a harvard student" "or _insert child prodigy here_" Example workflow "take a normal sheet of paper fold it hamburger style but then instead of folding it all the way to symmetry, give a quarter inch gap between the two folds then with the fold pointing to the right, fold it top-to-bottom 3 times unfoldthen write terms on outer flap, definitions on inner flap fold over, repeat ITS HAPPY. Ive done like 264 defines in 3 hours but actually a lot of perceived inefficiency or  failure /does/ come from shitty workflows once I have a system set up, the stuff practically teaches itself im just starting to hack school coursenotes: ocw formatting: latex killer ppts: magic markers THE LIST GOES ON." In parallel, as college students, were  SITTING ON GOLD.(e.g.  my friends coursenotes/annotated copy of Poems Poets Poetry is a GOLDMINE. like she should just republish the darn anthology with her notes. http://www.scotthyoung.com/blog/ makes his business off of this i want the workflow of someone super geniusly good - Jacob (and Riley) #good ',\
'Flow Cytometry App: I want someone to write an app that allows scientists to plan their flow panels without having to commit to the spectra of a single company.  some mobile applications exist, but these tend to be (a) clunky (b) slow (c) limited in accuracy.  Making a pretty graphical interface would not be hard, nor would importing libraries, just need a bench scientist to get together with a programmer.  There exist like many many bench scientist who would thank various deities for an effective mobile app.  I call bench scientist.  ~rileydrake@gmail.com or 443-854-7249',\
'what if you used an app to track when people actually /do/ take their medsthis is absolutely what we should be thinking aboutthere exist a number of drugs for which the main and important factor is the minimum blood level concentration is the important partamong these are birth control, seizure meds, beta-blockers and a whole bunch of other thingsand you have to take them at the same time every day because you need to maintain minimum effective concentrationbut, excepting beta-blockers, having a concentration in excess, up to about 3x the normal does, is not something that will hurt youso, what would be cooler than reminding you to take your meds when you tend to sit down and eat dinneris an app that analyzes when you actually do take your meds, and then suggests custom dosages based on your schedulecustom blister packs are actually not that hard, its something thats done a lot for people who are on oral chemo and want to take more on the weekends because they have to work during the weekits not something thats anywhere outside of the realm of physicians to prescribe, in fact, its actually in their best interest ~riled@mit.edu ',\
'i could write a tool to find people i would like to meet at MIT and surroundings based on how often they say "squeee" in chats ~jcole@mit.edu',\
'IdeaOverflow Bite-sized HackNY Project -- email ~jcole@mit.edu or call 858 740-6970... Looking for team member with graph visualization skills like d3, or text processing (or search or machine learning skills) Project: This is the single project about which I am currently most passionate in the world ~Jacob Cole',\
'Pitch-based scrolling - e.g. when you sing middle C, the document jumps to 50% mark. natural tool for voice recognition users/RSI/paralyzed patients',\
'EEG-based Slumping Detector -- detect the pattern of brain activity that correlates with slumping / program that alerts me as is my posture begins to deteriorate so that I could correct it.. Could also just tells you to go to sleep. Helps people recover more quickly from RSI/carpal tunnel. Has interesting neuro/psych implications if it works as well. Would use Emotiv headset ~jcole@mit.edu',\
'WorldThroughYourEyes -- What if you could make an app for Google Glasses or similar that follows a persons eyes and then and tracks where they are focusing. This way, you could  compare how different people focus differently, and analyze what that does to their lives. I also imagine that you could you could put on glasses yourself (or watch a screen), and then see the world through another persons eyes. ~jcole@mit.edu',\
'InstaBoxSite: platform to build: generalized, easy to modify "suggestion box" framework anyone can use to quickly build a website off that mold.  All of following sites and countless more are based on fundamentally the same idea of a "comments box: isawyou stackoverflow forums reddit fml formspring ideaoverflow.tk / hackathonprojects.tk suggestion box/politicalprogressbar ifiwereanmitstudent.tk tumblr twitter facebook wallIn parallel, I am able to protoype many of the websites I build these days with what is basically a google doc. Why not build a google doc with slightly more functionality that truly allows me to prototype these tools? Check out http://mitdocs.tk/ to see the potential of this. Relatedly, way for people to make a homepage as easily as they can make a google doc -- consider http://adamchu.tk/, and http://minimalisthomepages.tk/  ~jcole@mit.edu',\
'Tool to find song playing in background of youtube video, for instance, identify the following:  http://youtu.be/OWAMr_WrDK0?t=10m52s',\
'#idea virtual reality game with 3d-goggles in swimming pool. Or indoor skydiving arena that projects a zooming in Google Earth onto the floor below. Would be like <http://www.youtube.com/watch?v=gHo2eEVSqao> except with actual indoor skydiving than. Since while youre at terminal velocity you experience no toleration, this would be indistinguishable from actual skydiving (sans the initial drop), especially if you did this with virtual reality goggles. ~jcole@mit.edu',\
'Index card sharing -- A good way to organize your thoughts is to write them down concisely. An index card seems like a good length for a unit of thought: longer than a quote or decontextualized summary, shorter than a story or lesson. Index cards seem a good way to transmit thoughts: it is easy to learn information presented in bite-sized chunks, each centered around some principle you can easily remember. The title of the card can act as a "slogan" for the principle.',\
'I am inspired by Trefethens Index Cards: one mathematician wrote down his thoughts on science, education, politics, intelligence, etc. on ~350 index cards over a period of 40 years and published it as a book. (http://books.google.com/books/about/Trefethen_s_Index_Cards.html?id=hJT0tgAACAAJ)Minskys Society of Mind also strikes me as written in a similar way: while a page is more than an index card, the fact that each section is no more than a page has a focusing effect on the reader.',\
'There are two parts to this project: allowing the user to create a system of cards, and then facilitating sharing.',\
'Each index card has limited space but allows multimedia (for instance, putting in a simple picture/diagram as a symbol). You can hashtag index cards, search for others cards on similar topics, rate cards, provide links, and make "connections" between different cards (and possibly specify the kind of connection, for instance hierarchical), much like a semantic net. This gives a way to visualize someones thoughts (and almost "surf" their thoughts, in a way). I might have some good ideas which I write as a linear sequence of blog posts---but if I write them as index cards instead, this would force me to crystallize my ideas more, and allow them to be connected in a nonlinear fashion. Some possible uses: A card could be a quote, and then a anecdote around it. I could make one index card for every book I read, for instance---then anytime the book comes up in conversation I could pull up my index card on the phone and know exactly the thoughts I have about it, and be able to talk about it. (In fact, if I write up cards on a variety of topics, they could almost be a cheat sheet for conversation. If you had a repertoire of cards related to topics important to you, then you neednt grope for words, for instance, if someone asks about an aspect of your work. In fact, maybe they could check out your cards first, and the conversation could immediately proceed to something new!) I could use it for academics: a card could be a Theorem or Principle X, and contain the information I would need if, say, I had to give a talk on it on short notice. ~holden1@mit.edu #organizing thoughts [@Jacob: I overheard about this site in 6.868, and this idea has been on my mind for a while. Also, the IdeaOverflow idea is amazing!]',\
'Thoughtstream tool -- Make a central platform that integrates status messages, facebook posts blog posts, favorite quotes, and liked songs -- in other words, a platform for thoughtstreaming. Relates to many earlier ideas ~jcole@mit.edu [I was thinking about this. At the end of the day I want to look at all my writing activity (fb, reddit, chat), and choose to (or automatically) add things Ive written into my thought database. That way I can tag thoughts as I write, and not have to go back and search for them, or copy/paste in the moment ~ cj@cortexel.us ]',\
'Idea for a music project, to be performed at house parties. I tend to end up in beatbox/chant/drumming/freestyle vortices, inspiring deep conversation vortices, and vortices of the most ridiculous hilariousness. If I could record all of that from earlier in the party, and have bots layer these great moments together into music later -- music people could dance to, remember, and appreciate. . . O_O WOAH. ~cj@cortexel.us #music #peakexperience #generativemusic Woa....--Rafael',\
'Tool or music bot for quickly turning protest chants into generative hardcore/electro/punk/folk songs, on the spot, to be blasted through speakers and enjoyed at rallies and protests. ~cj@cortexel.us #protest #generativemusic #music',\
'Flow Me – Tool for making freestyling/rhyme/poetry unfairly easy. Suggests rhymes and alliterations as you type. Goal: to empower those with good messages and no writing skills. ~cj@cortexel.us #poetry #nlp #creativity #writing (Carl: check out http://tranquillpoet.com/ for inspiration!   Thank you!! That is awesome! This is a really elegant incarnation of the idea! Already getting a bunch of new ideas. Here are the beginnings of mine: http://cortexel.us/flow ) 3',\
'DeviceSymphony – mobile app/Web app that plays the same note you are singing, or plays harmonics to the note youre playing. This way, you could put all your mobile devices out on a table and sing and be accompanied by a whole orchestra! #<->backup singer app #music ~jcole@mit.edu #good',\
'App/Wii game/rock band extension that lets you be a conductor –when you point towards a certain section of the imaginary orchestra, certain notes would play. This relates to a humorous book I read a really long time ago called the armchair conductor ~jcole@mit.edu',\
'Scavenger Recipe App (aka Fridgey!) -- Enter what ingredients are present in your refrigerator, and it looks up possible recipes that include the ingredients entered, ranked by ratings and difficulty to make, for those days where you have a bunch of stuff in the fridge, but nothing to eat. This app can also log and track what ingredients you have available, so you do not have to enter your fridge inventory every time. A broke college students oasis. ~carlton.stafford@gmail.com  #<->FoodMom Comments:*Cool! They are definitely similar, but not the same, for one automatically orders ingredients you do not have, and the other shows you what you can make with what you do have. Combine them possibly?*Question: Would method of preparation be a worthy sub-category for the application? In other words, "Recipes that require baking, "Recipes to be prepared on a skillet." Or.. even better, "select the appliances/cooking materials accessible to you" (Can you suggest a less wordy way of saying this?) I am envisioning this in the form of a checklist. - acousticcole@gmail.com*A checklist, or perhaps a filter interface, where you check appliances available, and it filters out options that would not work. That may be a little easier. carlton.stafford@gmail.com	http://www.instantfundas.com/2010/08/15-websites-to-find-recipes-by.html <- it exists.',\
'Build eyetracking heatmap from laptop webcam -- useful for evaluating how you read different websites, self-tracking/optimizing, and evaluating websites you build. You could make a script that lets you compare different peoples reading styles and evaluate the eye movement patterns of master readers. Also for online chess you could track eye movement patterns of novices vs masters as part of the coaching -- this has been studied extensively. #cv ~hbedri@mit.edu  ~jcole@mit.edu',\
'Google docs optimized for instant web publishing #idea #good #lowhangingfruit ~jcole@mit.edu. An important facet is to combine with easy-to-remember domains like .tk. I was reinspired in the direction of this project after a resounding success building a collaborative doc, http://6034bonus.tk, for my AI class final notes yesterday; Google docs are great because theyre such a fast way to prototype so many web ideas. See also http://mitdocs.tk/ and derivatives. I wish they just created pages that were a bit more... web 2.0-y that were a pleasure to view as well as edit. Also, I wish you could do align left and align right on the right and left-hand sides of the same line. This is, I feel, the basis for an entirely new creative outlet. Is anybody who is good with node.js want to experiment with sharejs maybe? <http://sharejs.org/>? Note: doing so would be the stepping stone into a whole, tightly connected bunch of projects to which Ive given much thought and with which I am completely willing to help.  #<->Way to track traffic on Google Docs/quick way to assign a google doc to a .tk domain ',\
'Way to track traffic on Google Docs/quick way to assign a google doc to a .tk domain #<->Google docs optimized for instant web publishing ~jcole@mit.edu',\
'Emergency Pizza Button app -- One click pizza ordering via a big red button, modeled after the MIT east campus emergency pizza button.  Relatedly, I want to make "Push a button, get a cookie" app for Insomnia Cookies. ~jcole@mit.edu #active',\
'PhotoQuote -- app that lets you photograph a quote in a book, then searches online to find the boundaries of the quote youre probably looking to note down, and adds the quote to your notebook. I find myself photographing quotes all the time. This is a big idea, and knowing the thread of quotes a person is interested in is a very powerful, and truly relevant advertising dataset. #relates to "site that autocompletes quotes" #intentiondb',\
'Instaquote -- site that autocompletes quotes like instadefine.com  and it basically ends up letting you create a database  of quotes youre interested in and this is deep because quotes are your thoughts stated more clearly than you can state them yourself and if you make a db of all the quotes people think of  you get a huge window into their lives  it #relates to the power of status message logging. example:  is  send myself  email  of quotes I like  for instance  "and it scared me, having a wrong thought, because it meant my mind wasnt working properly"  from the curious incident of the dog in the night-time  i just was rereading today and i realized that was brilliant  because it relates to a concept  of avidya  in eastern philosophy the idea that there are some thoughts that we have that arent true, but instead  things that shouldnt bother us bother us  and when we think carefully and relax we can learn to only be bothered by the right things  (relatedly, theres a lot to be done with etymology) #intentiondb ~jcole@mit.edu',\
'online etymology tree #<->instadefine #<->admitsphere ~jcole@mit.edu +1 ~csvoss@mit.edu',\
'FoodMom -- App that tells you what to cook and automatically orders ingredients (or makes you a shopping list). Also suggest who you should cook with using the following meeting people strategy:" ~Jacob   +1 ~csvoss@mit.edu ~jcole@mit.edu #6.470 Meet people who have similar interests by matching people to each other who have mentioned titles to the same Wikipedia articles in their gmail chats, or used the same quotes. (Or it could look at your playlist history and match by music taste! (real "musicmatch")). Cooking/eating is one of the few anchors to physical world in an era of increasing digital distraction, and we should use it to resurrect classic face to face socialization. Ideas. Starts with http://foodlists.tk/ #primer #lifecoach',\
'-app that uses accelerometer data to detect when you (an old person) have fallen. If you dont touch a button in 1 min cancelling emergency call, it calls your relatives who check if youre okay, and broadcasts your gps location. ~jcole likes this one -- email me if you want to work on it! #<-> ginger.io #lowhanging #humandatamining #machinelearning  ~jcole@mit.edu',\
'-one-touch broadcast your current location (gps) to answer text msg ("where are you"). #easyui #lowhanging  ~jcole@mit.edu. #DONE, by Aaron Iba.',\
'ThisIsHowYouSoundRightNow (or ThisIsHowYouLookRightNow) -- app that determines if youre in "hack mode" or "lazy mode" (alertness level) by using machine learning on keystrokes. Make hack-o-meter. Also make it so that it shows a picture of you from webcam when youre drowsy so you look at yourself and see you need to go to sleep #humandatamining #machinelearning ~jcole@mit.edu',\
'Sphero app idea: make angry angry templar from SCII (http://us.battle.net/sc2/en/blog/7435938/Arcade_Highlight_%E2%80%9CAngry_Angry_Templar%E2%80%9D-9_28_2012) -- a sphero chases whoever is holding a sphero. Would use WifiSlam? #inprogress ~jcole@mit.edu',\
'App that tells you when to leave/what route to take so you dont get stuck in as bad of traffic. #relates to Social ridesharing app (search it on page) #lifeguiding ~jcole@mit.edu',\
'Organize related news articles into timelines so you can see the meaning of each article, and maybe join in! #intentiondb ~jcole@mit.edu',\
'Ambient information display app -- show imgs relevant to conversation by processing speech; e.g. saying i want to know if there is paint program for macs should autodisplay it. Inspired by Dougs #augmentedvirtuality ~jcole@mit.edu',\
'Wa (japanese word for personal peace) monitoring/regulating app. Maybe could use neural data. relates to gracegrader. peace within the mind leads to peace within the family, peace within the #humandatamining  ~jcole@mit.edu#machinelearning #intentiondb',\
'CuriosityThread -- Site that shows the chain of questions/interests a person asked/followed to gain the knowledge/passion they have. Perhaps to partially populate this site, Wikipedia could track threads of browsing, and scrolling. Subsequently, tutorials (even a textbook!) customized to the curiosity profiles of different people could be made of it? Relatedly, creating a web database of the series of questions bright students ask could be extremely powerful. I would love, for instance, to have documentation of the series of questions one of my friends asked over the course of his life to ultimately gain the knowledge to get gold at the International Chemistry Olympiad. #edu #<->admitsphere #<->whyisitawesome. #active, see http://curiositythread.tk/ or http://whyisitawesome.wikispaces.com/ ~jcole@mit.edu',\
'IdeaOverflow -- A place people can share good ideas that they dont necessarily have time to implement themselves online. I want to make a map, a connected graph, of all of peoples ideas (and implemented engineering projects) that shows the relationship of these projects to one another. At the borders of this graph would lie the ideas that are yet to be implemented -- investigating them more deeply would be analogous to exploring undiscovered terrain on a map. This tool would help people to come up with awesome ideas for hackathons, class projects, startups, and fun, and it also allow people to see  the trends/relationships in exciting ideas that are surging at a given point in time. Most of all, its inspiring to think that through this system, you could bring vitality to the education industry by reducing every class project to, at worst, implementing an idea that someone, somewhere would be really excited to build if they had the time to. #intentiondb ~jcole@mit.edu** Check out whatareyouworkingon.co by adleberg@princeton.edu',\
'PoliticalProgressBar -- I want to create a simple graphical interface that voters can use to quickly see what government is trying to accomplish and how far it has gotten towards achieving its goals -- it would perhaps take the form of a progress bar. More generally, the deeper significance of many news items can be revealed on interface such as this -- if a certain piece of sustainable energy legislation passes, how much closer has it gotten us as a nation and planet to actually being energy sustainable for the forseeable future? This system would graph that kind of information on timeline/progress bar, the position (% completion) of which could be determined roughly by a consensus of scholarly opinions. Above all, I want to make a database of thoughtful people and politicians dreams -- their collective positive visions for how the world should be -- then find the most rational way to make those dreams real (e.g. elect the senators that have the competence, vision, and concrete plans necessary. Are trickle down economics or Obamanomics better for creating a vibrant economy that allows people to live the American dream? I dont know. Lets look at the research and find out, and take the most rational action.) #intentiondb ~jcole@mit.edu',\
'explorable etymology graph -- would allow you to learn vocab both quickly and deeply. http://collegeappswiki.wikispaces.com/How+to+Memorize+Vocabulary #edu #<->admitsphere #instadefine ~jcole@mit.edu',\
'playlistforlife.com -- looks at what youre doing on pc and other devices and gives you the music for it! Or just compiles peoples coding playlists, jogging playlists, etc and lets you look them up, mix and match, etc. Could use stereotyping after learning to predict tastes #music  ~jcole@mit.eduAs an addendum, possibly be prodded to change playlist depending on activity of accelerometer in mobile device. Eg, when running, when driving/working. ~jaredlwong',\
'Real-time politifact analysis of political ads youre watching -- could be an app that listens to tv commercials that comes on and identifies them. could use http://www.politifact.com/truth-o-meter/article/2011/jun/24/politifact-app-now-available-iphone-and-other-devi/. #done WHOAH IT"S ALREADY BEEN DONE http://www.superpacapp.org/. #politicalscience ~jcole@mit.edu',\
'Mechanical Turk problems as reCaptcha -- service that lets you embed box that has ppl do specific types of mturk tasks AS the captcha challenges. have them do 2: one is super verified. the other less so.  Apparently, when you fill out some Google capchas it helps in Google street view For reading house numbers #hack ~jcole@mit.edu',\
'Better facebook search: you should be able to say something like "Jacob Cole MIT" and have it return Jacob Cole of MIT if such info is available (actually, im not sesarcheable :P) #eayui ~jcole@mit.edu',\
'Social ridesharing app --  If your friends or friends of friends (on fb, linkedin, gmail/google+, etc) are going in a similar direction, they can be advised to pick you up, and vice versa. This would avoid legal problems with hitchhiking (not to mention safety issues). And then you could bring on "friends of friends," people who work in same company as you, etc. to expand network into, ultimately, a general rideshare.'\
'Relatedly, CabShare: App that tells you whether anyone else in your vicinity is taking a cab to the same place or in the same direction. Finally, what if google maps had an integrated call a cab button when you searched directions. And/or what if this were integrated with Social Rideshare/Cabshare? Relates to database of intentions. #intentiondb #<->"App that tells you when to leave/what route to take so you dont get stuck in as bad of traffic>. #lifeguiding ~jcole@mit.edu',\
'Roommate-cancelling headphones: uses roommates laptop mic to seed noise cancellation alg in your headzphones (would this work?). -Update on sound canceling headphones that take feed from tv: how about ones that cancel people talking on the phone by receiving the phone signals and playing inverse sound waves. #signalprocessing ~jcole@mit.edu',\
'hackercasting -- streaming any or all of your screen, keystrokes, mic, and camera live while hacking, like twitchtv for hackers. EXTREMELY POWERFUL FOR EDUCATION/SPREADING HACKATHON CULTUREnow the trick is to get people to do it. Like recording good conversations, it just needs to be made ultraconvenient for it to start happening. We need to have a boxed tool and  get it announced by a charismatic and well-respected person at the beginning of hackathons saying "all competitors! Load up this tool to start broadcasting yourself live and become a coding Olympian, inspiring people all around the nation. Anybody ever wanted a league of skilled minions to follow and work on projects with you? This is the first step to becoming a hero and gaining adoring acolytes."This has the secondary effect of scaling exponentially and putting ordinary programmers into the shoes of inspiring leaders. I want my Mouse Army from Diamond Age. #edu #lowhanging #culturalengineering http://www.jacobblog.tpclubs.com/2012/08/hackercasting-a-big-idea/ ~jcole@mit.edu',\
'Create graph of all hackathon project ideas/startups to visualize connections/trends: at the borders are less connected ideas that need be explored-- just started here and heres the loader (takes a list like this one ~Jacob #visualization #intentiondb ~jcole@mit.edu',\
'newsdiffs.org — tracking changes in online news articles overtime. Github respository. https://github.com/ecprice/newsdiffs and articles in the New York Times:   #visualization #intentiondb https://www.nytimes.com/2012/07/01/opinion/sunday/article-changes-are-shown-in-a-tool-created-by-outsiders.html?_r=1&pagewanted=all',\
'Browser-based distributed computing API ~SETI@home with Chrome NaCl -- Mark Vismonte started on a JS version of this... #lowhanging  ~jcole@mit.edu',\
'WhosAround? -- way to send messages to only to people nearby you without them having to make their location public. Say I want to go boogie boarding with my friends in San Diego -- I send out an email/fb post to friends, with the filter currently in San Diego added. Then, only my friends whose GPS/IPs indicate that theyre currently in SD get the message.  Its not creepy/a waste of power (*cough* Daniel *cough*) like constantly geotracking people, and yet is in many ways a "gateway" into that world. This relates to Dougs "Bam" app that allows you to post "e-graffiti, digital messages tagged to a location. (This recreates the real-world phenomenon of being able to yell out and get the attention of only people near you -- in my mind the replication/generalization of real world phenomena in the digital world is a powerful heuristic #replicatesrealworld). relates to CommonPlace, "social networking for the neighborhood"  https://www.ourcommonplace.com/about #lowhanging  ~jcole@mit.edu',\
'Soft tissue pattern analysis -- machine learning takes webcam video feed and assess health by facial characteristics. Relatedly, whole body health, and posture assessor? Sees whole body. Relates to http://www.deepakchopraleela.com/ #humandatamining #machinelearning #intentiondb #computervision #taichi ~jcole@mit.edu',\
'Guard dog app -- uses network of data from all devices in house to determine where strange sound is coming from. Triangulation pinpoints location. If burglar is carrying a cell phone, also listens to cell traffic src to pick up on location. #<->Trespasser alert  ~jcole@mit.edu',\
'Trespasser alert -- detects if someone w/ a broadcasting device is in an off-limits area (perhaps this would be computer network app) #<->Guard dog app  Doorbell app -- texts you or dings if your doorbell rings? #lowhanging #<-> "one-touch broadcast your current location (gps) to answer text msg"',\
'Helpmefindmymom/helpmomfindme app -- 1 touch app for kids lost in a theme park. #lowhanging #<-> "one-touch broadcast your current location (gps) to answer text msg" #<-> "app that uses accelerometer data to detect when you (an old person) have fallen" ~jcole@mit.edu',\
'Who Do I Live Like? --  App that analyzes computer/smartphone use patterns of people throughout the day and tells them who they use the computer/smartphone like. Would figure out if hypersuccessful people use computer diifferently. Conversations, GPS patterns, etc? I feel like this data would be invaluable and enable droves of sociological research as well as an entirely new class of apps cen tered around guiding/shaping lifestyle. What gets measured gets managed -- this apps job would be to measure everything it can in the process uncovering the secrets to human behavior that can be deduced from things as subtle as accelerometer motion patterns. .This relates to my earlier post of this article -- this is the new frontier: AMAZING Application of Computer Usage Statistics: "How Depressives Surf the Web" http://www.nytimes.com/2012/06/17/opinion/sunday/how-depressed-people-use-the-internet.html?_r=1&hp. You could even give more government financial support to people who use their devices more healthily. ~jcole@mit.edu',\
'GraceGrader -- App that grades how graceful you are. Correlate this with other factors about a person. Maybe could even be used for marketing/healthcare. Could be done with iphone or even webcam/computer (webcam sees if your head stays level or jerks up and down).  Maybe could even tell if you slam the keys too hard using sound data (and speed data)!. Relates to ginger.io #lifetrackingJogging technique analysis app -- from machine learning of iphone app in pocket Relates to ginger.io #lifetracking ~jcole@mit.edu',\
'ClackerAlert -- tells if you slam the keys too hard using sound data (and speed/jerkiness data)!.Prevents RSI ~jcole@mit.edu',\
'FaceAverage -- Research shows that statistically speaking, if you average everybodys face dimensions in a room of say 20 people, you would end up with a very attractive face because those with blatant asymmetries, outliers on either end of the spectrum, would cancel each other out. Develop Facebook app that tests this amongst your friends. ~jcole@mit.edu  Handwriting match online either within your own sample or between you and famous person,  parallel to iwritelike.com ~jcole@mit.edu',\
'Fisheye lenses on laptops and iPhones so that they can see the whole room -- algorithmically undistort#~Jacob ~jcole@mit.edu',\
'Wouldnt it be cool if you could get captioning of an event via iphone? Either broadcast by service, or realtime speech recognition. You could preload the txt of the speech into system to make voice recog. more accurate. Relates to PA System ~jcole@mit.edu',\
'Slump-o-meter -- webcam (or other device!) based posture detector that tells you to go to sleep when the height of your head decreases too much during a session at the PC. A recent Stanford study showed that as the night progresses, people become progressively worse and the productivity decreases.  ~jcole@mit.edu',\
'iPhone gong/om app – App that sings the same note as you at a deep resonant freq OR app that makes many iPhones would resonate together to create a consistent resonating sound like a gong or "om" for use in meditation to harmonize brain wave activity. #~Jacob ~jcole@mit.edu',\
'iPhone backup singer/instrument app -- would play an electric organ or vocal tone that matches the pitch/harmonizes with that you are singing. #~Jacob ~jcole@mit.edu',\
'CloudDream -- creates cloud/ceiling popcorn patterns for artists to generate ideas for images. people see images in clouds: write a program that artists could use to overcome creativity barriers;  basically it would take a cloud formation image  and allow the artists to zoom in a specific part in incrementally improve something that resembles e.g. a giraffe until they have a full image. Its easier to "trace" something you "see" in  the random patterns than to draw it from scratch. Our brains find patterns in everything. #~Jacob ~jcole@mit.edu',\
'SpeechChat/Txting -- chat program that uses speech recognition/screenwriter to make it so that you can text/chat without ever looking at the screen. ~jcole@mit.edu',\
'BikeSting -- #hardware a chip embedded in a bike seat that gps tracks it when stolen then police place this around city watch when it gets stolen (it broadcasts its location to cell network) and catch the bike  theft rings then ppl are too scared to steal bikes cause they dont know if its being tracked ~jcole@mit.edu',\
'CuriosityThread -- Site that shows the chain of questions/interests a person asked/followed to gain the knowledge they have. Perhaps to partially populate this site, Wikipedia could track threads of browsing, and scrolling. Subsequently, tutorials (even a textbook!) customized to the curiosityprofiles of different people could be made of it? Relatedly, creating a web database of the series of questions bright students ask could be extremely powerful. I would love, for instance, to have documentation of the series of questions one of my friends asked over the course of his life to ultimatly gain the knowledge to get gold at the International Chemistry Olympiad. ~jcole@mit.edu',\
'LiveLog --  Evernote + twitter (+ etherpad?). .realtime blogging -- people can see your unformed scratch thought process. entries should be hashtagged and have live search by hashtag started frontend:  ~jcole@mit.edu',\
'WhereAreYou? app -- instead of txting your friends how long youll be when youre late you press 1 button and  it sends your location. could even integrate w/ txting/chat and see when someone msgs you "where are you"? and give you option to reply by WhereAreYou  #Completed http://glympse.com/ ~jcole@mit.edu',\
'GrabLunchWith app -- you press a button and it suggests where you should have lunch -- tries to recommend friends to go to same place so they meet. ~jcole@mit.edu',\
'Academic conversations tool (matches people to each other that have mentioned titles to the same Wikipedia articles in their chats), or quotes. Or music taste! (real "musicmatch") ~jcole@mit.edu',\
'Guitar hero typing tutor – letters fall down the screen, and make music when they cross the bar. By the end of it, you could use your keyboard as a musical instrument, because each key correlates with the note and you will be fluent into the nature of that correlation ~jcole@mit.edu',\
'"PA System" multiphone app -- 1 iPhone broadcasts microphone (or recording) into all iPhones in the room. very interesting paradigm. http://crowdsound.com/ -- not taken! Weve got to make a Gmail status message logger -- It would log your status and those of all of your friends. Doing this is of utmost sociological importance I my intuition tells me. Could do sentiment analysis and correlate w location, school, friends etc. Are we indeed the combo of our 5 closest friends? ~jcole@mit.edu',\
'COOL: iphone as mouse replacement app that you slide phone on desk. uses accelerometer. #good  ~jcole@mit.edu',\
'free food/reuse finder: app that parses free food/reuse mailing lists (as exist at MIT), and tells you if free items to grab/free food is near you. Helps less food get wasted, helps people who really want stuff get it 2nd hand (Carl: check out http://harvardfoodfinder.com for inspiration!)',\
'Nap Map App -- shows you where the closest good place to nap is (perhaps start on campus?) ~jcole@mit.edu',\
'Hacker casting – service that allows people to cast their screens while they are coding, also casts WebCam view of them, and also displays what keystrokes theyre making. This way, avid learners can watch and learn how pros code  ~jcole@mit.edu Kaleidoscope app – *relates to secret message reading app. Also, is there a magnifying glass app?word definer: uses OCR to define words its easy (maybe you would touch the word on the display that you want the definition for?). I can help/advise with this one ~jcole@mit.edu',\
'AirDraw -- Use accelerometer, and/or wifislam hyper accurate GPS data to make a mobile app that allows you to draw in the air. you could view your three-dimensional drawing by looking at it with your iPhone. In general see #<->"Window" into virtual world ~jcole@mit.edu',\
'"Window" into virtual world app: use the iPhone as a window to look at a virtual 3-D object that has been superimposed into real space. Would use accelerometer and Wi-Fi slam to make it so that when you move the iPhone around the object youd see it from different angles ~jcole@mit.edu',\
'IdeaOverflow: A place people can share good ideas that they dont necessarily have time to implement themselves online. I want to make a map, a connected graph, of all of peoples ideas (and implemented engineering projects) that shows the relationship of these projects to one another. At the borders of this graph would lie the ideas that are yet to be implemented -- investigating them more deeply would be analogous to exploring undiscovered terrain on a map. This tool would help people to come up with awesome ideas for hackathons, class projects, startups, and fun, and it also allow people to see  the trends/relationships in exciting ideas that are surging at a given point in time. Most of all, its inspiring to think that through this system, you could bring vitality to the education industry by reducing every class project to, at worst, implementing an idea that someone, somewhere would be really excited to build if they had the time to. ~jcole@mit.edu',\
'Mobile Apps:This is a long thread specifically from my mobile apps class -- some overlap from earlier:',\
'Here are some of my app ideas! Please tell me if youd like to work on any of these with me! ~jcole@mit.eduMultiphone apps, using Alex Lists Swyp: https://github.com/Swyp/swyp:-BigScreen (multiple iphones come together with make screen)-3D sound-multiple phones come together to make big keyboard ~ipad-"PA System"-gong iPhone app -- resonates multiple iPhones-IPhone "backup singers" (multiphone)-tuning fork iPhone app-Everyone watches same video or sees same site or plays same song-"telephone" game-do the wave app, beeps when you should lift arms -- could generalize to new public performance art form -group patterns for sports fans app-3D scanner (multiple phones or just one moving)-2 phones record/playback binaural data-Deckofcards -- allows for multiplayer poker (and other card games) -- PERFECT USE OF SWYP API-multiplayer game- game of catch or virtual tennis application',\
'Group of people takes pictures at scenic spot, automatic composite createdIf you allow, pic shared publically; enables supercomposite + time lapse. Maybe even adds result to google mapsPanorama from video',\
'Musical Instruments (e.g. miracas, tilt-based instrument, etc app). Giant (larger) Tonematrixapp that allows instant replay (recs the last 30 min?) of your conversations, music, or life in general (maybe could even ID the notes)vocal idea recorder app w/ fuzzy voice search. Also allows you to assoc photosapp that tells you if mutual friends/friends/people w/ shared interests are in area. Useful on train or on tours?fully functional graphing calculator on iPhone or cell phone in general. Would essentially emulate a TI-89 or TI-Nspire except would use multi-touch functionality to its advantage',\
'Political Progress Bar #in progressInstant Document Scan, from pic or video feed. Autocorrects quality/distortionAP English -- helps you keep track of stuff for AP english, allows you to scan your essays etc and use fuzzy ocr searchLecture recorder w/ fuzzy voice rec. searchApp that helps you stay on top of paperwork/gives you a schedule to get forms signed etcSpy thru fence by walking past and processing video feed',\
'OCR Word Search Solver Mouse replacement (use phone like you would ordinary external mouse, sliding on desc) #in progress',\
'Voice timbre extractor -- takes individual voices out of a crowdPachelbel alert: tells you if it hears pachelbel chords in song playingTone of voice detector -- tests if person is happy, or their emotion. Machine learning?',\
'Take photos (2 shots) for viewing with 3D glasses                          	power saver -- turns off power when you leave houseCircadian clock advisor, regulates sleTurns on lights as youre headed toward room?',\
'App that helps you relax and keep balanced lifestyleActigraph -- figures out when youre going to sleep perhaps Playlistforlife.com -- songs to play that go with w/e youre doingWhatshouldIdo? Helps you schedule your day thru time-based recommendations/opportunities in your area/friend networks, plus:WhatdoIwanttodo? Go thru binary search (would you prefer A) or B) to find what you want to eat)20 questions beaterchess/checkers/connect4 board analyzeranagram solver (photo-based or input based)App you can ask what a def of a word is.App that disables sound during prescheduled times or in preidentified places',\
'WhatdoIwant to eat? Go thru binary search to find what you want to eat',\
'App that analyzes vital sign from image/video?PTSD treatment appSpeech recognition subtitles for conversations (could do auto translation too?). App that lets you make a phone call thru a human or automatic translation service.Voice recognition texting + screen reader response for complete hands free accessRecipe app with verbal or tonal scrolling. Map of free wifi netwApp that keeps track of everything you buy automatically (wireless dl from cashier?) so it has an inventory of orks in area, in and out of rangeApp that lets you make money by permitting subscribed users use your phone as a wifi uplinkGlobal temp data trackingTide app w/ GPS.App that tells you best surf break to go to based on tide/conditions. Maybe suggests a board as well?virtual golf swing analyzer?fishing game?-iPhone or smartphone app that uses an algorithm to figure out who should order what food at a restaurant and split what with whom in order to satisfy the most people for the lowest cost (users would input what they would like and how important something is - or if it is a must-have - and how important money is, or how much money they had)',\
'way to make payments by phone instead of physical credit cardApp that suggests when people should schedule to go places for least traffic -- it would work together w/ other users to stagger timesApp that broadcast data to let nearby noise cancelling headsets try to cancel your voiceIPhone based id -- lets authorized security services instantly get an image of your face on their screen as you walk in so you dont need to pull out your idSupercamera -- takApp that grades your driving by accelerationes 500 consecutive photos and composites/steadycams them.',\
'"Holding a baby chicken" App that helps you move gently and gracefully. Grades your grace?App that tries to perform accelerometer-based odometryJogging/biking pacer app',\
'IPhone as segway sensor arrayApp to read secret physical secret messages that others have left, or id secret signsNight Vision app (IR? or light amplification)UV detectorMusic page turner that listens to youPiano playing graderFace recognizer in crowdPhotograph an equation to auto-graph it. Auto-interpolator of data points on visual chartEasyDefine OCRInstaDefine.com appbook companion -- has hard words that appear in book, in order, and searcheable like instadefineApp that interpolates where wifi in nearby area signals are coming from (you have to walk from point to point before it can triangulate)Guard dog -- uses network of data from all devices in house to determine where strange sound is coming from. Triangulation pinpoints location. If burglar is carrying a cell phone, also listens to cell traffic src to pick up on location.Trespasser alert -- detects if someone w/ a broadcasting device is in an off-limits area (perhaps this would be computer network app)Doorbell app -- texts you or dings if your doorbell rings?Helpmefindmymom/helpmomfindme app -- for kids lost in a theme park. "Panic Pin" -- separate pin that you can tell someone if forced to identify your PIN (idea from idea about credit cards)Guest login on phone?',\
'Research shows that statistically speaking, if you average everybodys face dimensions in a room of say 20 people, you would end up with a very attractive face because those with blatant asymmetries, outliers on either end of the spectrum, would cancel each other out. Develop mobile or Facebook app that tests this amongst your friends.Website/iPhone app that algorithmically grades beauty. Put large disclaimer at the bottom.Makeup iPhone app: tells where to put makeup to transform face to make it most attractivehttp://en.wikipedia.org/wiki/Aesthetics ... nformationKolgomoroff complexity relates to beauty! Even in art!',\
'-- Jacob Coleqoɔɐɾ',\
'Massachusetts Institute of TechnologyDepartment of Electrical Engineering and Computer Sciencejcole@mit.edu | (858) 740-6970Jacob J Cole (jcole@mit.edu) Posts: 20Joined: Tue Feb 08, 2011 9:07 pmTopRe: IDEAS!by Trevor B Walker (trebawa@mit.edu) » Sat Feb 04, 2012 3:11 pm',\
'I like a lot of these idea! For the recipe app, it would be cool if it could parse recipes and then automatically display the next step, along with a timer if one is needed.Trevor B Walker (trebawa@mit.edu) Posts: 1Joined: Wed Sep 07, 2011 9:13 pmTopRe: IDEAS!by Abubakar Abid (aabid93@mit.edu) » Sat Feb 04, 2012 3:56 pm',\
'Wow, this list is quite broad. Im not sure if this is what you mean by "App to read secret physical secret messages that others have left, or id secret signs, but I would like to make an app that makes the real world like a scratchpad for people to leave messages and other people to read them. So, wherever you are, you just open the app and read messages that other people have left at that location or write your own. One implementation could be like a virtual graffiti app, but it doesnt necessarily have to be linked with physical structures. Not sure if something like this has already been done.Abubakar Abid (aabid93@mit.edu) Posts: 2Joined: Tue Sep 06, 2011 8:51 amTopRe: IDEAS!by Eric Lubin (eblubin@mit.edu) » Sat Feb 04, 2012 4:10 pm',\
'Wow. very interesting ideas. heres my input:',\
'the instadefine.com client seems pretty straightforward. do they have an API? either way, simple enough idea I like it.',\
'as for a graphing calculator, check out https://www.abettercalculator.com/. Its a web app that lets you graph functions and is pretty well developed. it used to be java-based but was rewritten from the ground up in HTML5 so is now usable on iOS.',\
'The video-based panorama picture app sounds pretty cool also, (maybe just take multiple pictures and stitch together)?',\
'I think Im most interested in a deck of cards app. it could be very interesting using Bluetooth to play locally. one phone is designated the dealer and then everyone is dealt cards that only they can see. there would be a place to put down cards (face up or face down). and maybe we could include iPad support where the iPad would represent the table where the "community" cards are stored. the scrabble app makes use of this fuctionality. where the iPad is the board and each phone has each players set of letters to play. anyone feel free to expand upon this. just some food for thoughtEric Lubin (eblubin@mit.edu) Posts: 6Joined: Thu Sep 08, 2011 1:02 pmTopRe: IDEAS!by Laia Mogas-soldevila (dumo@mit.edu) » Sat Feb 04, 2012 5:07 pm',\
'Hey Jacob,I may be interested in : 3D scanner (multiple phones or just one moving)I would like to develop an architecture and energy related app.(see my post)..Laia Mogas-SoldevilaMIT Massachusetts Institute of TechnologyDepartment of Architecture | Computational Design Groupdumo@mit.edu | Barcelona Spain | Cambridge MALaia Mogas-soldevila (dumo@mit.edu) Posts: 3Joined: Wed Sep 07, 2011 5:29 pmLocation: cambridge , maTopRe: IDEAS!by Jacob J Cole (jcole@mit.edu) » Sun Feb 05, 2012 7:19 am',\
'Abubakar Abid (aabid93@mit.edu) wrote:Wow, this list is quite broad. Im not sure if this is what you mean by "App to read secret physical secret messages that others have left, or id secret signs, but I would like to make an app that makes the real world like a scratchpad for people to leave messages and other people to read them. So, wherever you are, you just open the app and read messages that other people have left at that location or write your own. One implementation could be like a virtual graffiti app, but it doesnt necessarily have to be linked with physical structures. Not sure if something like this has already been done.',\
'a) I meant an app that that would be able to read, for instance, a hidden QR code thats concealed steganographically in, for instance, an innocent looking image of a lolcat. What if, to help people living in censored environments get information from the outside world, you made an app that would be able to read certain class of information codes hidden in images. The police would have trouble scanning every single postcard that enters a country, and you couldnt exactly get someone in trouble for possessing a postcard that has a hidden image in it if they claim not to know about claim (well, if the justice system works at all in such countries). This is just a completely out their brainstorm, but it kind of a cool thought. ',\
'b) A friend of mine who might actually be taking this class made this virtual graffiti app -- its really cool! thebamapp.comJacob J Cole (jcole@mit.edu) Posts: 20Joined: Tue Feb 08, 2011 9:07 pmTopRe: IDEAS!by Katharine M Daly (dalyk@mit.edu) » Sun Feb 05, 2012 6:27 pm',\
'I like a lot of the ideas Jacob has posted here. Im interested in OCR and/or audio recognition stuff, so the essay scanning, subtitles for conversations (+ translation), or the piano grader apps stood out for me. The best idea I had come up with so far was to use OCR to convert vocab lists at the end of textbook chapters or words in the glossary into flashcards that the user could study using their phone. This would be targeted towards middle school and high school students who have vocab quizzes. There seemed to be a lot of flashcard apps in the Android market, but none that I saw skipped the time-consuming part of having to enter in all the text for the flashcards yourself.-KatharineKatharine M Daly (dalyk@mit.edu) Posts: 2Joined: Fri Feb 11, 2011 11:41 amTopRe: IDEAS!by Eric Lubin (eblubin@mit.edu) » Sun Feb 05, 2012 11:52 pm',\
'There seems to be a few iOS apps that integrate with quizlet (http://itunes.apple.com/us/app/flashcar ... 99818?mt=8) for flash cards. But I do agree taking it one step further to streamline user input of data through OCR would be neat. Anyone interested in the deck of cards idea?Eric Lubin (eblubin@mit.edu) Posts: 6Joined: Thu Sep 08, 2011 1:02 pmTopRe: IDEAS!by Jacob J Cole (jcole@mit.edu) » Mon Feb 06, 2012 1:08 pm',\
'IWantA -- app that you input a list of items you want into that in turn lists all of the different ways you can get something based on whats available local to you, the Internet, etc. Then, when you happen to be nearing the date of the special sale, or a place where you can buy something, your iPhone notifies you. For instance, I want a bike, not urgently, and as cheaply as possible. I missed the Cambridge bike auction last term because I wasnt thinking about it, but now I wish I had gone to it -- I wish my iPhone app had notified me that there was the bike auction because I had a bike on my wish list. I could also buy one at Cambridge bicycles, but its too expensive. However, there are cheaper bike shops further out of town. Next time I travel further out of town near cheap bike shop, it would have been continued.Additionally, Im missing a glove right now. while visiting Yale, I actually notice that theres a North face store that I walked past like 3 times, and except for my inhibitions about absurd price, I would have bought the glove. Now I think it would have been worth it simply due to the convenience.Additionally, this could be integrated with social networking so that if your friends are near a place to pick something up for you, it would notify them as well. Heck, you could eventually do it with random strangers with sufficient "reputation points, and maybe pay people for their troubles. The more reputable you are, the higher value tasks youre given.Jacob J Cole (jcole@mit.edu) Posts: 20Joined: Tue Feb 08, 2011 9:07 pmTopRe: IDEAS!by Jacob J Cole (jcole@mit.edu) » Tue Feb 07, 2012 12:16 am',\
'Experience capture. When something amazing, like a volcano eruption starts to happen, everyone in a tour group pulls out their phones together and, with a mixture of excitement, awe, and reverence starts recording the scene from slightly different angles. This would allow for full immersive three-dimensional panoramic virtual reality, three-dimensional sound image capture, and would be an amazing shared social experience to boot. Its sort of like when all of the Navi in avatar connect their nervous system-hair to the great tree to transfer Jake from one body to the other.',\
'UILab -- toolset that allows you to design UI and UX for any kind of app, and then builds it from there. Would have elastic rectangles as div-like "boxes," you could click on them and make them nonelastic if you wanted. More generally you could edit the UIs of existing applications using a system like this',\
're: meeting other people at hackathon/checking in at event  -- talk to jacob (the guy who pitched a million things) or hisham or tejas or shri or zac',\
'History-Tree: Browser plugin uses your browsing history to predict which pages you will visit next. This can help you in two key ways: Lets say you are currently reading the New York Times. After reading NYT, you always go to the Economist. Once the plugin notices this pattern, it can make this transition seamless. Whenever you press some hotkey, it will show you which websites you commonly browse to next in a small tree. Secondly, the plugin pre-loads these pages, to make them render instantly once you choose to view them.',\
'Website that allows instant food ordering with a press of a button',\
'Anyway, the basic idea  is just to make the ideas site usable for people trying to come up with good class projects, science fair projects,  independent  projects etc.  I have ideas for  a pretty simple interface Ill talk about soon.',\
'Mostly, I want to do this because I personally have >10 projects that are just itching to be made real, like right this second, and I know that there are  plenty of people who would be excited to work on them. I would want to have a nominal foot in them, but I cant possibly do them all myself. I know good things will happen if we pull this together. -Political progress bar: lists all current initiatives by government, and shows where each of them are. This could be used to  coordinate disjoint congressional activity.-App that lets you use a phone as a replacement for computer mouse. Instead of having to carry around an actual mouse, use your phone!  Would use accelerometer and/or camera. Its not been done before, though http://mobilemouse.com/ is related #~Jacob-Slump-o-meter -- webcam based posture detector-T9 Predictive Keyboard Layout for PC-Guitar hero typing tutor? Typing tutor that plays musical notes when you hit each key. you hit all the keys just right, it plays a song! Maybe it could be like guitar hero, where accompaniment is automatically added.',\
'How about a  Netflix-algorithm-based scholarship matching site  (you get matched to people you are like, its not a blind search. I have an exact vision as how to do it)?  The same engine can be used to help you find activities on campus  or in your area.'\
'FaceAverage -- if you were to average all of the parameters of the faces of  people in a relatively large room, the resulting face would likely be very attractive, because it is extremely balanced. app/Web app that automatically merges faces-Dormhole (MIT-Stanford Wormhole++)Lets put a 3D TV in our floor lounge and make it into a 3D wormhole between colleges (Dormhole!)-Princeton 3D sound technology for speakers --->-face-recognition technology to match you with the other college that has the most interesting person to you, based on concepts mentioned in GChats and FB friends---> get grant to build a larger one in student center afterwards. Use expensive 3D tv that works w/o glasses',\
'-iPhone backup singer/instrument app -- would play an electric organ or vocal tone that matches the pitch that you are singing. #~Jacob- approximate voice-recognition search of YouTube videos- quizlet aggregator.-voice recognition/text-to-speech hybrid texting or chat client. Then you could talk via headset w/o being near machine!-filter that can tune to a specific voice timbre, so it can hear what an individual is saying in noisy room-noise canceling headsets that network with your roommates computer microphone to cancel out precisely what theyre saying before it reaches you',\
'-iPhone gong/om app – many iPhones would resonate together to create a consistent resonating sound like a gong or "om" for use in meditation to harmonize brain wave activity. #~JacobUse  machine learning and/orsentiment analysis of peoples  personalities/saying/doings on social networks to help  people make college decisions.',\
' Science projects: Is it impossible to construct a macro scale Brownian ratchet?Investigate under  what circumstances and to what extent photons motion is influenced by the item projecting them. For instance, if you have a laser sideways, the photons move sideways. But if you move the laser forward and backwards, the photons velocity is not affected. Why is this?Can a strategy such as Beal and Sussmans controlled hallucination algorithm beat Captcha in theory?',\
'-***GOOD IDEA*** ***COMMERCIALLY VIABLE*** web site that has a bunch of real peoples embedded lists of scholarships that they applied to/are applying to. it would list the basic description of the person, their skills, their achievements, their interests, and the list of scholarships that they are applying to.  What this would allow people to view is essentially find a person similar to them (maybe even income if anonymous) and see the scholarships of the person applied to.  This arose from a bunch of people asking me for a list of scholarships that I applied to. This is better than simply searching blindly on scholarship match web sites because it circumvents the individual scholarship vetting process; people dont apply to use the scholarships, or at least they wouldnt include them in the lists they submit. the key is to make this easy, like simply asking a friend for a list of scholarships.  The lists could either be plain text, or parsed by a regular expression that will naturalistically interpret the input to identify the deadlines and titles and links to each scholarship. Another useful feature would be to have a username based lookup so that friends can share their own lists. Only a simple database of initial lists is necessary to begin this process; 20 or so profiles perhaps.']

